from enum import StrEnum


class ConfidenceLevel(StrEnum):
    VERIFIED = "VERIFIED"
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    MEDIUM_CONFIDENCE = "MEDIUM_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNVERIFIED = "UNVERIFIED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONFLICT = "CONFLICT"


class UserRole(StrEnum):
    STUDENT = "student"
    ADMIN = "admin"


class ExperienceLevel(StrEnum):
    STUDENT = "student"
    ENTRY_LEVEL = "entry_level"
    JUNIOR = "junior"
    MID = "mid"
    SENIOR = "senior"


class SelfReportedSkillLevel(StrEnum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class MemoryCategory(StrEnum):
    DEMONSTRATED_SKILL = "demonstrated_skill"
    DEMONSTRATED_WEAKNESS = "demonstrated_weakness"
    CAREER_GOAL = "career_goal"
    LEARNING_PREFERENCE = "learning_preference"
    COMPLETED_ACTIVITY = "completed_activity"
    PROJECT_DECISION = "project_decision"
    ASSESSMENT_RESULT = "assessment_result"
    INTERVIEW_WEAKNESS = "interview_weakness"


class MemorySource(StrEnum):
    USER_REPORTED = "USER_REPORTED"
    SYSTEM_OBSERVED = "SYSTEM_OBSERVED"
    ASSESSMENT_DERIVED = "ASSESSMENT_DERIVED"
    AI_INFERRED = "AI_INFERRED"


class UserPhase(StrEnum):
    ONBOARDING = "ONBOARDING"
    CAREER_DISCOVERY = "CAREER_DISCOVERY"
    CAREER_SELECTION = "CAREER_SELECTION"
    ROLE_RESEARCH = "ROLE_RESEARCH"
    BASELINE_ASSESSMENT = "BASELINE_ASSESSMENT"
    LEARNING = "LEARNING"
    PRACTICE = "PRACTICE"
    INDEPENDENT_TEST = "INDEPENDENT_TEST"
    WEAKNESS_RETRAIN = "WEAKNESS_RETRAIN"
    PROJECT_PLANNING = "PROJECT_PLANNING"
    PROJECT_BUILD = "PROJECT_BUILD"
    PROJECT_DEFENSE = "PROJECT_DEFENSE"
    APTITUDE = "APTITUDE"
    SOFT_SKILLS = "SOFT_SKILLS"
    MOCK_INTERVIEW = "MOCK_INTERVIEW"
    READINESS_REVIEW = "READINESS_REVIEW"
    CONTINUOUS_IMPROVEMENT = "CONTINUOUS_IMPROVEMENT"


class MasteryLevel(StrEnum):
    UNKNOWN = "UNKNOWN"
    LEARNING = "LEARNING"
    PRACTICING = "PRACTICING"
    PROFICIENT = "PROFICIENT"
    HIGH_CONFIDENCE_MASTERY = "HIGH_CONFIDENCE_MASTERY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class SkillSource(StrEnum):
    USER_REPORTED = "USER_REPORTED"
    ASSESSMENT_DERIVED = "ASSESSMENT_DERIVED"
    SYSTEM_OBSERVED = "SYSTEM_OBSERVED"
    AI_INFERRED = "AI_INFERRED"


class MasteryState(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    LEARNING = "LEARNING"
    PRACTICING = "PRACTICING"
    DEMONSTRATED = "DEMONSTRATED"
    MASTERED = "MASTERED"


class ReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class InferenceType(StrEnum):
    VERIFIED_FACT = "VERIFIED_FACT"
    HIGH_CONFIDENCE_INFERENCE = "HIGH_CONFIDENCE_INFERENCE"
    UNCERTAIN = "UNCERTAIN"
    UNVERIFIED = "UNVERIFIED"
