from enum import StrEnum


class ConfidenceLevel(StrEnum):
    VERIFIED = "VERIFIED"
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    MEDIUM_CONFIDENCE = "MEDIUM_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNVERIFIED = "UNVERIFIED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONFLICT = "CONFLICT"


class UserRole(StrEnum):
    STUDENT = "student"
    ADMIN = "admin"


class UserPhase(StrEnum):
    ONBOARDING = "ONBOARDING"
    CAREER_DISCOVERY = "CAREER_DISCOVERY"
    CAREER_SELECTION = "CAREER_SELECTION"
    ROLE_RESEARCH = "ROLE_RESEARCH"
    BASELINE_ASSESSMENT = "BASELINE_ASSESSMENT"
    LEARNING = "LEARNING"
    PRACTICE = "PRACTICE"
    INDEPENDENT_TEST = "INDEPENDENT_TEST"
    WEAKNESS_RETRAIN = "WEAKNESS_RETRAIN"
    PROJECT_PLANNING = "PROJECT_PLANNING"
    PROJECT_BUILD = "PROJECT_BUILD"
    PROJECT_DEFENSE = "PROJECT_DEFENSE"
    APTITUDE = "APTITUDE"
    SOFT_SKILLS = "SOFT_SKILLS"
    MOCK_INTERVIEW = "MOCK_INTERVIEW"
    READINESS_REVIEW = "READINESS_REVIEW"
    CONTINUOUS_IMPROVEMENT = "CONTINUOUS_IMPROVEMENT"


class MasteryLevel(StrEnum):
    UNKNOWN = "UNKNOWN"
    LEARNING = "LEARNING"
    PRACTICING = "PRACTICING"
    PROFICIENT = "PROFICIENT"
    HIGH_CONFIDENCE_MASTERY = "HIGH_CONFIDENCE_MASTERY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class InferenceType(StrEnum):
    VERIFIED_FACT = "VERIFIED_FACT"
    HIGH_CONFIDENCE_INFERENCE = "HIGH_CONFIDENCE_INFERENCE"
    UNCERTAIN = "UNCERTAIN"
    UNVERIFIED = "UNVERIFIED"
